name: "Build container images"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extrace short sha
        id: short-sha
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/rinx/gcloud-auth-proxy:latest
            ghcr.io/rinx/gcloud-auth-proxy:${{ steps.short-sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/rinx/gcloud-auth-proxy
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true
